name: Run Selenium Tests

on: [push]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-cache-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Chromium browser
      uses: actions/cache@v3
      with:
        path: /usr/bin/chromium-browser
        key: ${{ runner.os }}-chromium-cache-${{ hashFiles('config/.env.dev') }}
        restore-keys: |
          ${{ runner.os }}-chromium-cache-

    - name: Install Chromium for Selenium
      run: |
        if [ ! -f /usr/bin/chromium-browser ]; then
          echo "Chromium not found in cache. Installing Chromium..."
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          if [ ! -f /usr/bin/google-chrome ]; then
            sudo ln -s /snap/bin/chromium /usr/bin/google-chrome
          fi
        else
          echo "Chromium found in cache."
        fi

    - name: Set up environment variables
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
        echo "HEADLESS=true" >> $GITHUB_ENV

    - name: Run pytest
      run: |
        echo "Base URL: $BASE_URL"
        pytest