name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Test with Pytest
    runs-on: ubuntu-latest  # You can specify macos-latest or windows-latest based on your needs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python version
        with:
          python-version: 3.12  # You can specify the desired Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Set up environment variables (optional)
        run: echo "ACCESS_OPTIONS=some_value" >> $GITHUB_ENV
        # You can set other environment variables or load them from GitHub secrets as needed

      - name: Run tests with environment (dev/staging/prod)
        run: pytest --env=dev  # You can change this to `staging` or `prod`
        env:
          BASE_URL: ${{ secrets.BASE_URL }}


