name: Run Pytest UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install browser for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run Pytest tests
      run: |
        pytest --maxfail=1 --disable-warnings -v
