name: Run UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chromium for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        if [ ! -f /usr/bin/google-chrome ]; then
          sudo ln -s /snap/bin/chromium /usr/bin/google-chrome
        fi

    - name: Run UI tests
      run: |
        pytest -v